#! /usr/bin/env python
# import binascii
# -*-coding:UTF-8-*-
import os
import sys
import operator
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

# from readexcel.readexcel_WorkingDirectoryGen import readexcel_WorkingDirectoryGen
from readexcel.readexcel_VIP import readexcel_VIP
# from readexcel.readexcel_DutSignal import readexcel_DutSignal
# from readexcel.readexcel_ClockRst import readexcel_Clock Rst
from common_lib.parameters import Parameters

class gen_axi_uvc:

    def __init__(self):
        print("[gen_xx_sequence_lib]:initial")
        #EnvironmentGenCfg='../VerifyEnvironmentGenCfg.xlsx'
        EnvironmentGenCfg=Parameters.EnvironmentGenCfg
        # readexcel_WorkingDirectoryGen.readexcel_WorkingDirectoryGen_info(self,EnvironmentGenCfg,PrintEnable=False)
        readexcel_VIP.readexcel_VIP_info(self,EnvironmentGenCfg,PrintEnable=False)
        readexcel_VIP.readexcel_VIP_AXI_info(self,EnvironmentGenCfg,PrintEnable=False)
        # readexcel_ClockRst.readexcel_ClockRst_info(self,EnvironmentGenCfg,PrintEnable=False)
        # readexcel_DutSignal.readexcel_DutSignal_info(self,EnvironmentGenCfg,PrintEnable=False)
        self.gen_axi_uvc_info(PrintEnable=False)
        

    def gen_axi_uvc_info(self,PrintEnable):
        #############################axi_UvcTop.svh########################################################
        filename = open("axi_UvcTop.svh", "w+")
        filename.write("`ifndef _AXI_UVC_TOP_SVH\n")
        filename.write("`define _AXI_UVC_TOP_SVH\n")
        filename.write("\n")
        filename.write("`include \"uvm_macros.svh\"\n")
        filename.write("\n")
        filename.write("package axi_UvcTop;\n")
        filename.write("\timport uvm_pkg::*;\n")
        filename.write("\n")
        filename.write("\t/** Import the SVT UVM PKG **/\n")
        filename.write("\timport svt_uvm_pkg::*;\n")
        filename.write("\n")
        filename.write("\t/** Import the AXI VIP **/\n")
        filename.write("\timport svt_axi_uvm_pkg::*;\n")
        filename.write("\n")
        filename.write("\ttypedef class axi_cust_config;\n")
        filename.write("\ttypedef class axi_base_seq;\n")
        filename.write("\n")
        filename.write("\t`include \"axi_cust_config.sv\";\n")
        filename.write("\t`include \"axi_sequence_lib.sv\";\n")
        filename.write("\n")
        filename.write("endpackage\n")
        filename.write("\n")
        filename.write("`endif\n")
        filename.close()
        #############################axi_cust_config.sv########################################################
        filename = open("axi_cust_config.sv", "w+")
        filename.write("`ifndef _AXI_CUST_CONFIG_SV\n")
        filename.write("`define _AXI_CUST_CONFIG_SV\n")
        filename.write("\n")
        filename.write("`define PRJ_AXI_NUM_MASTERS %s\n"%self.VIP_DB['AXI']['VipMasterNum'])
        filename.write("`define PRJ_AXI_NUM_SLAVES  %s\n"%self.VIP_DB['AXI']['VipSlaveNum'])
        filename.write("\n")
        filename.write("class axi_cust_config extends uvm_object;\n")
        filename.write("    svt_axi_system_configuration    axi_cfg;\n")
        filename.write("\n")
        filename.write("    `uvm_object_utils_begin(axi_cust_config)\n")
        filename.write("        `uvm_field_object(axi_cfg,UVM_DEFAULT)\n")
        filename.write("    `uvm_object_utils_end\n")
        filename.write("\n")
        filename.write("    function new(string name=\"axi_cust_config\");\n")
        filename.write("        super.new(name);\n")
        filename.write("\n")
        filename.write("        axi_cfg=new(\"axi_cfg\");\n")
        filename.write("\n")
        filename.write("        axi_cfg.num_masters=`PRJ_AXI_NUM_MASTERS;\n")
        filename.write("        axi_cfg.num_slaves =`PRJ_AXI_NUM_SLAVES;\n")
        filename.write("        axi_cfg.system_monitor_enable=0;\n")
        filename.write("\n")
        filename.write("        //Create port configurations\n")
        filename.write("        axi_cfg.create_sub_cfgs(`PRJ_AXI_NUM_MASTERS,`PRJ_AXI_NUM_SLAVES);\n")
        filename.write("        axi_cfg.common_clock_mode=1;\n")
        filename.write("\n")
        filename.write("        //timeout cfg\n")
        filename.write("        axi_cfg.bus_inactivity_timeout  =256000000;\n")
        filename.write("\n")
        filename.write("        axi_cfg.awready_watchdog_timeout=256000000;\n")
        filename.write("        axi_cfg.wdata_watchdog_timeout  =256000000;\n")
        filename.write("        axi_cfg.wready_watchdog_timeout =256000000;\n")
        filename.write("\n")
        filename.write("        axi_cfg.bresp_watchdog_timeout  =256000000;\n")
        filename.write("        axi_cfg.bready_watchdog_timeout =256000000;\n")
        filename.write("\n")
        filename.write("        axi_cfg.arready_watchdog_timeout=256000000;\n")
        filename.write("        axi_cfg.rdata_watchdog_timeout  =256000000;\n")
        filename.write("        axi_cfg.rready_watchdog_timeout =256000000;\n")
        filename.write("\n")
        for i in range(self.VIP_DB['AXI']['VipMasterNum']):
            MasterID="Master%s"%i
            filename.write("        // cfg of master%s\n"%i)
            filename.write("        axi_cfg.master_cfg[%s].is_active    =1;\n")
            filename.write("        axi_cfg.master_cfg[%s].addr_width   =%s;\n"%(i,self.VIP_DB_Feature['AXI'][MasterID]['AddrWidth']))
            filename.write("        axi_cfg.master_cfg[%s].data_width   =%s;\n"%(i,self.VIP_DB_Feature['AXI'][MasterID]['DataWidth']))
            filename.write("        axi_cfg.master_cfg[%s].id_width     =%s;\n"%(i,self.VIP_DB_Feature['AXI'][MasterID]['IdWidth']))
            filename.write("\n")
            filename.write("        axi_cfg.master_cfg[%s].axi_interface_type   =svt_axi_port_configuration::AXI4;\n")
            filename.write("        axi_cfg.master_cfg[%s].memory_update_for_read_xact_enable=1;\n")
            filename.write("        axi_cfg.master_cfg[%s].silent_mode=1;\n")
            filename.write("\n")
        for i in range(self.VIP_DB['AXI']['VipSlaveNum']):
            SlaveID="Slave%s"%i
            filename.write("        // cfg of slave%s\n"%i)
            filename.write("        axi_cfg.slave_cfg[%s].is_active    =1;\n")
            filename.write("        axi_cfg.slave_cfg[%s].addr_width   =%s;\n"%(i,self.VIP_DB_Feature['AXI'][SlaveID]['AddrWidth']))
            filename.write("        axi_cfg.slave_cfg[%s].data_width   =%s;\n"%(i,self.VIP_DB_Feature['AXI'][SlaveID]['DataWidth']))
            filename.write("        axi_cfg.slave_cfg[%s].id_width     =%s;\n"%(i,self.VIP_DB_Feature['AXI'][SlaveID]['IdWidth']))
            filename.write("\n")
            filename.write("        axi_cfg.slave_cfg[%s].axi_interface_type   =svt_axi_port_configuration::AXI4;\n")
            filename.write("        axi_cfg.slave_cfg[%s].max_num_outstanding_xacts_check_enable=1;\n")
            filename.write("        axi_cfg.slave_cfg[%s].exclusive_access_enable               =1;\n")
            filename.write("        axi_cfg.slave_cfg[%s].port_interleaving_enable              =1;\n")
            filename.write("        axi_cfg.slave_cfg[%s].read_data_interleaving_size           =4;\n")
            filename.write("        axi_cfg.slave_cfg[%s].port_interleaving_group_id            =1;\n")
            filename.write("        axi_cfg.slave_cfg[%s].read_data_reordering_depth            =8;\n")
            filename.write("        axi_cfg.slave_cfg[%s].reordering_algorithm                  =svt_axi_port_configuration::ROUND_ROBIN;\n")
            filename.write("        //axi_cfg.slave_cfg[%s].reordering_algorithm                =svt_axi_port_configuration::RANDOM;\n")
            filename.write("        axi_cfg.slave_cfg[%s].device_xact_Sent_from_interleaved_port=1;\n")
            filename.write("\n")
            filename.write("        axi_cfg.slave_cfg[%s].num_outstanding_xact                  =-1;//256;\n")
            filename.write("        axi_cfg.slave_cfg[%s].num_outstanding_snoop_xact            =256;\n")
            filename.write("        axi_cfg.slave_cfg[%s].num_read_outstanding_xact             =256;\n")
            filename.write("        axi_cfg.slave_cfg[%s].num_write_outstanding_xact            =256;\n")
            filename.write("\n")
            filename.write("        //axi_cfg.slave_cfg[%s].exlusive_access_enable              =1;\n")
            filename.write("        //axi_cfg.slave_cfg[%s].max_num_exlusive_access             =10;\n")
            filename.write("        //axi_cfg.slave_cfg[%s].enable_delayed_responese_port       =1;\n")
            filename.write("        //axi_cfg.slave_cfg[%s].initialize_output_signals_at_start  =1;\n")
            filename.write("        //axi_cfg.slave_cfg[%s].protocol_checks_enable              =0;\n")
            filename.write("        axi_cfg.slave_cfg[%s].silent_mode                           =1;\n")
            filename.write("\n")

        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("endclass\n")
        filename.write("\n")
        filename.write("`endif\n")
        filename.close()
        #############################axi_sequence_lib.sv########################################################
        filename = open("axi_sequence_lib.sv", "w+")
        filename.write("`ifndef _AXI_SEQUENCE_LIB_SV\n")
        filename.write("`define _AXI_SEQUENCE_LIB_SV\n")
        filename.write("\n")
        # axi_slave_base_seq
        filename.write("class axi_slave_base_seq extends svt_axi_slave_base_sequence;\n")
        filename.write("\n")
        filename.write("    axi_cust_config   axi_cfg;\n")
        filename.write("\n")
        filename.write("    `uvm_object_utils_begin(axi_slave_base_seq)\n")
        filename.write("        `uvm_field_object(axi_cfg,UVM_DEFAULT)\n")
        filename.write("    `uvm_object_utils_end\n")
        filename.write("\n")
        filename.write("    function new(string name=\"axi_slave_base_seq\");\n")
        filename.write("        super.new(name);\n")
        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("    virtual task pre_start();\n")
        filename.write("        //`uvm_info(get_full_name(),\"pre_start\",UVM_LOW)\n")
        filename.write("        if(starting_phase!=null)\n")
        filename.write("            starting_phase.raise_objection(this)\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("    virtual task post_start();\n")
        filename.write("        //`uvm_info(get_full_name(),\"post_start\",UVM_LOW)\n")
        filename.write("        if(starting_phase!=null)\n")
        filename.write("            starting_phase.raise_objection(this)\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("    virtual task body();\n")
        filename.write("        //`uvm_info(get_full_name(),\"body\",UVM_LOW)\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("endclass\n")
        filename.write("\n")
        # axi_master_base_seq
        filename.write("class axi_master_base_seq extends svt_axi_master_base_sequence;\n")
        filename.write("\n")
        filename.write("    axi_cust_config   axi_cfg;\n")
        filename.write("\n")
        filename.write("    `uvm_object_utils_begin(axi_master_base_seq)\n")
        filename.write("        `uvm_field_object(axi_cfg,UVM_DEFAULT)\n")
        filename.write("    `uvm_object_utils_end\n")
        filename.write("\n")
        filename.write("    function new(string name=\"axi_master_base_seq\");\n")
        filename.write("        super.new(name);\n")
        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("    virtual task pre_start();\n")
        filename.write("        //`uvm_info(get_full_name(),\"pre_start\",UVM_LOW)\n")
        filename.write("        if(starting_phase!=null)\n")
        filename.write("            starting_phase.raise_objection(this);\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("    virtual task post_start();\n")
        filename.write("        //`uvm_info(get_full_name(),\"post_start\",UVM_LOW)\n")
        filename.write("        if(starting_phase!=null)\n")
        filename.write("            starting_phase.raise_objection(this);\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("    virtual task body();\n")
        filename.write("        //`uvm_info(get_full_name(),\"body\",UVM_LOW)\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("endclass\n")
        filename.write("\n")
        # axi_slave_mem_responense_seq
        filename.write("class axi_slave_mem_response_seq extends axi_slave_base_seq;\n")
        filename.write("\n")
        filename.write("    bit[15:0]ADDR_READY_DELAY_MIN;\n")
        filename.write("    bit[15:0]ADDR_READY_DELAY_MAX;\n")
        filename.write("    bit[15:0]DATA_WEADY_DELAY_MIN;\n")
        filename.write("    bit[15:0]DATA_WEADY_DELAY_MAX;\n")
        filename.write("\n")
        filename.write("    bit[15:0]RVALID_DELAY_MIN;\n")
        filename.write("    bit[15:0]RVALID_DELAY_MAX;\n")
        filename.write("    bit[15:0]BVALID_DELAY_MIN;\n")
        filename.write("    bit[15:0]BVALID_DELAY_MAX;\n")
        filename.write("\n")
        filename.write("    svt_axi_slave_transaction   req_resp;\n")
        filename.write("\n")
        filename.write("    `uvm_object_utils(axi_slave_mem_response_seq)\n")
        filename.write("\n")
        filename.write("    function new(string name=\"axi_slave_mem_response_seq\");\n")
        filename.write("        super.new(name);\n")
        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("    virtual task body();\n")
        filename.write("        integer             status;\n")
        filename.write("        svt_configuration   get_cfg;\n")
        filename.write("\n")
        filename.write("        `uvm_info(get_type_name(),\"body() Entered ...\",UVM_LOW)\n")
        filename.write("\n")
        filename.write("        p_sequencer.get_cfg(get_cfg);\n")
        filename.write("        if(!$cast(cfg, get_cfg))begin\n")
        filename.write("            `uvm_fatal(get_type_name(),\"Unable to $cast the configuration to a svt_axi_port_configuration class\")\n")
        filename.write("        end\n")
        filename.write("\n")
        filename.write("        //consumes responses sent by driver\n")
        filename.write("        sink_responses();\n")
        filename.write("        forever begin\n")
        filename.write("            p_sequencer.response_request_port.peek(req_resp);\n")
        filename.write("            status=req_resp.randomize with{\n")
        filename.write("                enable_interleave==1;\n")
        filename.write("                bresp inside{\n")
        filename.write("                    svt_axi_slave_transaction::OKAY,\n")
        filename.write("                    svt_axi_slave_transaction::EXOKAY};\n")
        filename.write("\n")
        filename.write("                foreach(rresp[index]){\n")
        filename.write("                    rresp[index]inside{\n")
        filename.write("                        svt_axi_slave_transaction::OKAY,\n")
        filename.write("                        svt_axi_slave_transaction::EXOKAY};\n")
        filename.write("                }\n")
        filename.write("                req_resp.addr_ready_delay inside{[ADDR_READY_DELAY_MIN:ADDR_READY_DELAY_MAX]};\n")
        filename.write("                foreach(req_resp.wready_delay[i]){\n")
        filename.write("                    req_resp.wready_delay[i] inside{[DATA_WEADY_DELAY_MIN:DATA_WEADY_DELAY_MAX]};\n")
        filename.write("                }\n")
        filename.write("                if(req_resp.xact_type==svt_axi_slave_transaction::WRITE){\n")
        filename.write("                    req_resp.bvalid_delay inside{[BVALID_DELAY_MIN:BVALID_DELAY_MAX]};\n")
        filename.write("                }\n")
        filename.write("                if(req_resp.xact_type==svt_axi_slave_transaction::READ){\n")
        filename.write("                    foreach(req_resp.rvalid_delay[i]){\n")
        filename.write("                        req_resp.rvalid_delay[i] inside{[RVALID_DELAY_MIN:RVALID_DELAY_MAX]};\n")
        filename.write("                    }\n")
        filename.write("                }\n")
        filename.write("            };\n")
        filename.write("\n")
        filename.write("            if(!status)\n")
        filename.write("                `uvm_fatal(get_type_name(),\"body():Unable to randomize a response!!!\")\n")
        filename.write("\n")
        filename.write("            if(req_resp.get_transmitted_channel()==svt_axi_slave_transaction::WRITE)begin\n")
        filename.write("                `protect\n")
        filename.write("                    put_write_transaction_data_to_mem(req_resp);\n")
        filename.write("                `endprotect\n")
        filename.write("            end\n")
        filename.write("            else if(req_resp.get_transmitted_channel()==svt_axi_slave_transaction::READ)begin\n")
        filename.write("                `protect\n")
        filename.write("                    get_read_data_from_mem_to_transaction(req_resp);\n")
        filename.write("                `endprotect\n")
        filename.write("            end\n")
        filename.write("\n")
        filename.write("            $cast(req,req_resp);\n")
        filename.write("\n")
        filename.write("            `uvm_send(req);\n")
        filename.write("        end\n")
        filename.write("        `uvm_info(get_type_name(),\"body():Exiting ...\",UVM_LOW)\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("endclass\n")
        filename.write("\n")
        # axi_master_wr_directed_seq
        filename.write("class axi_master_wr_directed_seq extends axi_master_base_seq;\n")
        filename.write("\n")
        filename.write("    rand bit[63:0]  write_addr;\n")
        filename.write("    rand bit[1023:0]write_data[];\n")
        filename.write("    rand bit[31:0]  burst_len;\n")
        filename.write("    constraint c_burst_len{\n")
        filename.write("        write_data.size()==burst_len\n")
        filename.write("        soft  burst_len inside{[1:128]};\n")
        filename.write("        solve burst_len before write_data; \n")
        filename.write("    }\n")
        filename.write("    constraint c_write_addr{\n")
        filename.write("        soft write_addr inside{['h0:'hffff]};\n")
        filename.write("    }\n")
        filename.write("    `uvm_object_utils(axi_master_wr_directed_seq)\n")
        filename.write("\n")
        filename.write("    function new(string name=\"axi_master_wr_directed_seq\");\n")
        filename.write("        super.new(name);\n")
        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("    virtual task body();\n")
        filename.write("        svt_axi_master_transaction  write_tran;\n")
        filename.write("        svt_configuration           get_cfg;\n")
        filename.write("        super.body();\n")
        filename.write("        p_sequencer.get_cfg(get_cfg);\n")
        filename.write("        if(!cast(cfg,get_cfg))begin\n")
        filename.write("            `uvm_fatal(\"body\",\"Unable to $cast the configuration to a svt_axi_port_configuration class\");\n")
        filename.write("        end\n")
        filename.write("        `uvm_create(write_tran)\n")
        filename.write("        write_tran.port_cfg     =cfg;\n")
        filename.write("        write_tran.xact_type    =svt_axi_transaction::WRITE;\n")
        filename.write("        write_tran.addr         =write_addr;\n")
        filename.write("        write_tran.burst_type   =svt_axi_transaction::INCR;\n")
        filename.write("        write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_128BIT;\n")
        filename.write("        write_tran.atomic_type  =svt_axi_transaction::NORMAL;\n")
        filename.write("        write_tran.burst_length =burst_len;\n")
        filename.write("        write_tran.data         =new[write_tran.burst_length];\n")
        filename.write("        write_tran.wstrb        =new[write_tran.burst_length];\n")
        filename.write("        write_tran.data_user    =new[write_tran.burst_length];\n")
        filename.write("        write_tran.wvalid_delay =new[write_tran.burst_length];\n")
        filename.write("        foreach(write_tran.data[i])begin\n")
        filename.write("            write_tran.data[i]=write_data[i];\n")
        filename.write("        end\n")
        filename.write("        foreach(write_tran.wstrb[i])begin\n")
        filename.write("            write_tran.wstrb[i]=128'hffffffff;\n")
        filename.write("        end\n")
        filename.write("        foreach(write_tran.wvalid_delay[i])begin\n")
        filename.write("            write_tran.wvalid_delay[i]=0;\n")
        filename.write("        end\n")
        filename.write("        `uvm_send(write_tran)\n")
        filename.write("        get_response(rsp);\n")
        filename.write("        `uvm_info(\"body\",\"AXI WRITE transaction completed\",UVM_LOW)\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("endclass\n")
        filename.write("\n")
        # axi_master_rd_directed_seq
        filename.write("class axi_master_rd_directed_seq extends axi_master_base_seq;\n")
        filename.write("\n")
        filename.write("    rand bit[63:0]  read_addr;\n")
        filename.write("    rand bit[1023:0]read_data[];\n")
        filename.write("    rand bit[31:0]  burst_len;\n")
        filename.write("    constraint c_burst_len{\n")
        filename.write("        read_data.size()==burst_len\n")
        filename.write("        soft  burst_len inside{[1:128]};\n")
        filename.write("        solve burst_len before read_data; \n")
        filename.write("    }\n")
        filename.write("    constraint c_read_addr{\n")
        filename.write("        soft read_addr inside{['h0:'hffff]};\n")
        filename.write("    }\n")
        filename.write("    `uvm_object_utils(axi_master_rd_directed_seq)\n")
        filename.write("\n")
        filename.write("    function new(string name=\"axi_master_rd_directed_seq\");\n")
        filename.write("        super.new(name);\n")
        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("    virtual task body();\n")
        filename.write("        svt_axi_master_transaction  read_tran;\n")
        filename.write("        svt_configuration           get_cfg;\n")
        filename.write("        super.body();\n")
        filename.write("        p_sequencer.get_cfg(get_cfg);\n")
        filename.write("        if(!cast(cfg,get_cfg))begin\n")
        filename.write("            `uvm_fatal(\"body\",\"Unable to $cast the configuration to a svt_axi_port_configuration class\");\n")
        filename.write("        end\n")
        filename.write("        `uvm_create(read_tran)\n")
        filename.write("        read_tran.port_cfg     =cfg;\n")
        filename.write("        read_tran.xact_type    =svt_axi_transaction::WRITE;\n")
        filename.write("        read_tran.addr         =read_addr;\n")
        filename.write("        read_tran.burst_type   =svt_axi_transaction::INCR;\n")
        filename.write("        read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_128BIT;\n")
        filename.write("        read_tran.atomic_type  =svt_axi_transaction::NORMAL;\n")
        filename.write("        read_tran.burst_length =burst_len;\n")
        filename.write("        read_tran.data         =new[read_tran.burst_length];\n")
        filename.write("        read_tran.wstrb        =new[read_tran.burst_length];\n")
        filename.write("        read_tran.data_user    =new[read_tran.burst_length];\n")
        filename.write("        foreach(read_tran.rready_delay[i])begin\n")
        filename.write("            read_tran.rready_delay[i] =0;\n")
        filename.write("        end\n")
        filename.write("        `uvm_send(read_tran)\n")
        filename.write("        get_response(rsp);\n")
        filename.write("        foreach(rsp.data[i])begin\n")
        filename.write("            read_data[i]=rsp.data[i];\n")
        filename.write("        end\n")
        filename.write("        `uvm_info(\"body\",\"AXI READ transaction completed\",UVM_LOW)\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("endclass\n")
        filename.write("\n")
        # axi_master_wr_nb_directed_seq
        filename.write("class axi_master_wr_nb_directed_seq extends axi_master_base_seq;\n")
        filename.write("\n")
        filename.write("    rand bit[63:0]  write_addr;\n")
        filename.write("    rand bit[1023:0]write_data[];\n")
        filename.write("    rand bit[31:0]  burst_len;\n")
        filename.write("    rand bit[15:0]  CfgBurst;\n")
        filename.write("    constraint c_burst_len{\n")
        filename.write("        write_data.size()==burst_len;\n")
        filename.write("        soft  burst_len inside{[1:128]};\n")
        filename.write("        solve burst_len before write_data; \n")
        filename.write("    }\n")
        filename.write("    constraint c_write_addr{\n")
        filename.write("        soft write_addr inside{['h0:'hffff]};\n")
        filename.write("    }\n")
        filename.write("    `uvm_object_utils(axi_master_wr_nb_directed_seq)\n")
        filename.write("\n")
        filename.write("    function new(string name=\"axi_master_wr_nb_directed_seq\");\n")
        filename.write("        super.new(name);\n")
        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("    virtual task body();\n")
        filename.write("        svt_axi_master_transaction  write_tran;\n")
        filename.write("        svt_configuration           get_cfg;\n")
        filename.write("        super.body();\n")
        filename.write("        p_sequencer.get_cfg(get_cfg);\n")
        filename.write("        if(!cast(cfg,get_cfg))begin\n")
        filename.write("            `uvm_fatal(\"body\",\"Unable to $cast the configuration to a svt_axi_port_configuration class\");\n")
        filename.write("        end\n")
        filename.write("        `uvm_create(write_tran)\n")
        filename.write("        write_tran.port_cfg     =cfg;\n")
        filename.write("        write_tran.xact_type    =svt_axi_transaction::WRITE;\n")
        filename.write("        write_tran.addr         =write_addr;\n")
        filename.write("        write_tran.burst_type   =svt_axi_transaction::INCR;\n")
        filename.write("        //write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_128BIT;\n")
        filename.write("             if(CfgBurst==1024) write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_128BIT;\n")
        filename.write("        else if(CfgBurst==512)  write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_512BIT;\n")
        filename.write("        else if(CfgBurst==256)  write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_256BIT;\n")
        filename.write("        else if(CfgBurst==128)  write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_128BIT;\n")
        filename.write("        else if(CfgBurst==64)   write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_64BIT;\n")
        filename.write("        else if(CfgBurst==32)   write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_32BIT;\n")
        filename.write("        else if(CfgBurst==16)   write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_168BIT;\n")
        filename.write("        else if(CfgBurst==8)    write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_8BIT;\n")
        filename.write("        else                    write_tran.burst_size   =svt_axi_transaction::BURST_SIZE_1024BIT;\n")
        filename.write("        write_tran.atomic_type  =svt_axi_transaction::NORMAL;\n")
        filename.write("        write_tran.burst_length =burst_len;\n")
        filename.write("        write_tran.data         =new[write_tran.burst_length];\n")
        filename.write("        write_tran.wstrb        =new[write_tran.burst_length];\n")
        filename.write("        write_tran.data_user    =new[write_tran.burst_length];\n")
        filename.write("        write_tran.wvalid_delay =new[write_tran.burst_length];\n")
        filename.write("        foreach(write_tran.data[i])begin\n")
        filename.write("            write_tran.data[i]=write_data[i];\n")
        filename.write("        end\n")
        filename.write("        foreach(write_tran.wstrb[i])begin\n")
        filename.write("            //write_tran.wstrb[i]=128'hffffffff;\n")
        filename.write("                 if(CfgBurst==1024) write_tran.wstrb[i]   =128'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;\n")
        filename.write("            else if(CfgBurst==512)  write_tran.wstrb[i]   = 64'hFFFFFFFFFFFFFFFF                ;\n")
        filename.write("            else if(CfgBurst==256)  write_tran.wstrb[i]   = 32'hFFFFFFFF                        ;\n")
        filename.write("            else if(CfgBurst==128)  write_tran.wstrb[i]   = 16'hFFFF                            ;\n")
        filename.write("            else if(CfgBurst==64)   write_tran.wstrb[i]   =  8'hFF                              ;\n")
        filename.write("            else if(CfgBurst==32)   write_tran.wstrb[i]   =  4'hF                               ;\n")
        filename.write("            else if(CfgBurst==16)   write_tran.wstrb[i]   =  2'h3                               ;\n")
        filename.write("            else if(CfgBurst==8)    write_tran.wstrb[i]   =  1'h1                               ;\n")
        filename.write("            else                    write_tran.wstrb[i]   =128'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;\n")
        filename.write("        end\n")
        filename.write("        foreach(write_tran.wvalid_delay[i])begin\n")
        filename.write("            write_tran.wvalid_delay[i]=0;\n")
        filename.write("        end\n")
        filename.write("        `uvm_send(write_tran)\n")
        filename.write("        get_response(rsp);\n")
        filename.write("        `uvm_info(\"body\",\"AXI WRITE transaction completed\",UVM_LOW)\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("endclass\n")
        filename.write("\n")
        # axi_master_rd_nb_directed_seq
        filename.write("class axi_master_rd_nb_directed_seq extends axi_master_base_seq;\n")
        filename.write("\n")
        filename.write("    rand bit[63:0]  read_addr;\n")
        filename.write("    rand bit[1023:0]read_data[];\n")
        filename.write("    rand bit[31:0]  burst_len;\n")
        filename.write("    rand bit[15:0]  CfgBurst;\n")
        filename.write("    constraint c_burst_len{\n")
        filename.write("        read_data.size()==burst_len;\n")
        filename.write("        soft  burst_len inside{[1:128]};\n")
        filename.write("        solve burst_len before read_data; \n")
        filename.write("    }\n")
        filename.write("    constraint c_write_addr{\n")
        filename.write("        soft read_addr inside{['h0:'hffff]};\n")
        filename.write("    }\n")
        filename.write("    `uvm_object_utils(axi_master_rd_nb_directed_seq)\n")
        filename.write("\n")
        filename.write("    function new(string name=\"axi_master_rd_nb_directed_seq\");\n")
        filename.write("        super.new(name);\n")
        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("    virtual task body();\n")
        filename.write("        svt_axi_master_transaction  read_tran;\n")
        filename.write("        svt_configuration           get_cfg;\n")
        filename.write("        super.body();\n")
        filename.write("        p_sequencer.get_cfg(get_cfg);\n")
        filename.write("        if(!cast(cfg,get_cfg))begin\n")
        filename.write("            `uvm_fatal(\"body\",\"Unable to $cast the configuration to a svt_axi_port_configuration class\");\n")
        filename.write("        end\n")
        filename.write("        `uvm_create(read_tran)\n")
        filename.write("        read_tran.port_cfg     =cfg;\n")
        filename.write("        read_tran.xact_type    =svt_axi_transaction::WRITE;\n")
        filename.write("        read_tran.addr         =read_addr;\n")
        filename.write("        read_tran.burst_type   =svt_axi_transaction::INCR;\n")
        filename.write("        //read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_128BIT;\n")
        filename.write("             if(CfgBurst==1024) read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_128BIT;\n")
        filename.write("        else if(CfgBurst==512)  read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_512BIT;\n")
        filename.write("        else if(CfgBurst==256)  read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_256BIT;\n")
        filename.write("        else if(CfgBurst==128)  read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_128BIT;\n")
        filename.write("        else if(CfgBurst==64)   read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_64BIT;\n")
        filename.write("        else if(CfgBurst==32)   read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_32BIT;\n")
        filename.write("        else if(CfgBurst==16)   read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_168BIT;\n")
        filename.write("        else if(CfgBurst==8)    read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_8BIT;\n")
        filename.write("        else                    read_tran.burst_size   =svt_axi_transaction::BURST_SIZE_1024BIT;\n")
        filename.write("        read_tran.atomic_type  =svt_axi_transaction::NORMAL;\n")
        filename.write("        read_tran.burst_length =burst_len;\n")
        filename.write("        read_tran.data         =new[read_tran.burst_length];\n")
        filename.write("        read_tran.rready_delay =new[read_tran.burst_length];\n")
        filename.write("        read_tran.data_user    =new[read_tran.burst_length];\n")
        filename.write("        foreach(read_tran.rready_delay[i])begin\n")
        filename.write("            read_tran.rready_delay[i]=0;\n")
        filename.write("        end\n")
        filename.write("        `uvm_send(read_tran)\n")
        filename.write("        get_response(rsp);\n")
        filename.write("        foreach(read_tran.data[i])begin\n")
        filename.write("            read_data[i]=rsp.data[i];\n")
        filename.write("        end\n")
        filename.write("        `uvm_info(\"body\",\"AXI READ transaction completed\",UVM_LOW)\n")
        filename.write("    endtask\n")
        filename.write("\n")
        filename.write("endclass\n")
        filename.write("\n")
        filename.write("`endif\n")
        filename.close()

        if PrintEnable==True:
            print("Please define the infomation of printing that you need!!!")
 
            
if __name__ == '__main__':
    gen=gen_axi_uvc()