#!/usr/bin/env python3
# -*-coding:UTF-8-*-
# ============================================================
# MyUvmGen_v2.0 — 寄存器自测试 Sequence 生成器
#
# 【设计说明】
# 生成三类标准寄存器自测试 sequence:
#   1. reg_access_seq: 复位值读回检查 + 读写比对
#   2. reg_bit_bash_seq: walking-1/walking-0 位翻转测试
#   3. reg_stress_seq: 随机读写压力测试
#
# 【UVM 方法论要点】
# - 寄存器测试应通过前门访问 (reg.write/reg.read via adapter)
# - reg.mirror() 用于比对镜像值和期望值
# - uvm_reg::predict() 用于更新镜像值（后门访问场景）
# - 自测试 sequence 应独立可运行，不依赖其他 sequence
# ============================================================
import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
from common_lib.parameters import Parameters

class gen_reg_sequence:

    def __init__(self):
        print("[gen_reg_sequence]: initial")
        self.gen_reg_sequence_info(tb_name='xx', PrintEnable=True)

    def gen_reg_sequence_info(self, tb_name, PrintEnable=False):
        filename = open("%s_reg_sequence.sv" % tb_name, "w+", encoding="utf-8")
        
        filename.write("`ifndef _%s_REG_SEQUENCE_SV_\n" % tb_name.upper())
        filename.write("`define _%s_REG_SEQUENCE_SV_\n")
        filename.write("\n")
        filename.write("//=========================================================================\n")
        filename.write("// %s_reg_sequence: 寄存器自测试 Sequence 库\n" % tb_name)
        filename.write("//   包含:\n")
        filename.write("//   - %s_reg_access_seq: 复位值检查 + 读写比对\n" % tb_name)
        filename.write("//   - %s_reg_bit_bash_seq: 位翻转 (walking-1/walking-0)\n" % tb_name)
        filename.write("//   - %s_reg_stress_seq: 随机读写压力测试\n" % tb_name)
        filename.write("//=========================================================================\n")
        filename.write("\n")

        # ===== 1. Reg Access Sequence =====
        filename.write("//=========================================================================\n")
        filename.write("// %s_reg_access_seq: 访问测试\n" % tb_name)
        filename.write("//   Step 1: 读取所有寄存器的复位值，与期望值比对\n")
        filename.write("//   Step 2: 对每个 RW 寄存器执行 写→读→比对\n")
        filename.write("//=========================================================================\n")
        filename.write("class %s_reg_access_seq extends uvm_sequence;\n" % tb_name)
        filename.write("\n")
        filename.write("    %s_reg_block  regmodel;\n" % tb_name)
        filename.write("    uvm_status_e  status;\n")
        filename.write("    uvm_reg_data_t value;\n")
        filename.write("\n")
        filename.write("    `uvm_object_utils(%s_reg_access_seq)\n" % tb_name)
        filename.write("    function new(string name=\"%s_reg_access_seq\");\n" % tb_name)
        filename.write("        super.new(name);\n")
        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("    virtual task body();\n")
        filename.write("        uvm_reg regs[$];\n")
        filename.write("        uvm_reg_data_t rdata;\n")
        filename.write("        int pass_cnt, fail_cnt;\n")
        filename.write("\n")
        filename.write("        `uvm_info(get_type_name(), \"===== Register Access Test Start =====\", UVM_LOW)\n")
        filename.write("\n")
        filename.write("        // 获取 reg_block（从 config_db 或 sequence 内置）\n")
        filename.write("        if (regmodel == null) begin\n")
        filename.write("            `uvm_fatal(get_type_name(), \"regmodel is null! Must be set before starting.\")\n")
        filename.write("        end\n")
        filename.write("\n")
        filename.write("        // 获取所有寄存器\n")
        filename.write("        regmodel.get_registers(regs);\n")
        filename.write("        pass_cnt = 0;\n")
        filename.write("        fail_cnt = 0;\n")
        filename.write("\n")
        filename.write("        `uvm_info(get_type_name(), $sformatf(\"Total registers: %%0d\", regs.size()), UVM_LOW)\n")
        filename.write("\n")
        filename.write("        foreach (regs[i]) begin\n")
        filename.write("            string rname = regs[i].get_full_name();\n")
        filename.write("\n")
        filename.write("            `uvm_info(get_type_name(), $sformatf(\"Testing register: %%s\", rname), UVM_MEDIUM)\n")
        filename.write("\n")
        filename.write("            // ---------- Step 1: Read reset value ----------\n")
        filename.write("            regs[i].read(status, rdata, UVM_FRONTDOOR);\n")
        filename.write("            if (status != UVM_IS_OK) begin\n")
        filename.write("                `uvm_error(get_type_name(), $sformatf(\"Read failed: %%s\", rname))\n")
        filename.write("            end\n")
        filename.write("            else begin\n")
        filename.write("                uvm_reg_data_t exp_val = regs[i].get_reset();\n")
        filename.write("                bit mismatch = 0;\n")
        filename.write("                // 检查每个 field 的复位值\n")
        filename.write("                uvm_reg_field fields[$];\n")
        filename.write("                regs[i].get_fields(fields);\n")
        filename.write("                foreach (fields[j]) begin\n")
        filename.write("                    uvm_reg_data_t fval = (rdata >> fields[j].get_lsb_pos()) & ((1 << fields[j].get_n_bits()) - 1);\n")
        filename.write("                    uvm_reg_data_t fexp = fields[j].get_reset();\n")
        filename.write("                    if (fval !== fexp) begin\n")
        filename.write("                        `uvm_error(get_type_name(), $sformatf(\n")
        filename.write("                            \"Reset mismatch: %%s.%%s: exp=%%0h, got=%%0h\",\n")
        filename.write("                            rname, fields[j].get_name(), fexp, fval))\n")
        filename.write("                        mismatch = 1;\n")
        filename.write("                    end\n")
        filename.write("                end\n")
        filename.write("                if (!mismatch) begin\n")
        filename.write("                    `uvm_info(get_type_name(), $sformatf(\"  PASS: %%s reset check\", rname), UVM_HIGH)\n")
        filename.write("                    pass_cnt++;\n")
        filename.write("                end\n")
        filename.write("                else begin\n")
        filename.write("                    fail_cnt++;\n")
        filename.write("                end\n")
        filename.write("            end\n")
        filename.write("\n")
        filename.write("            // ---------- Step 2: Write → Read back (RW fields only) ----------\n")
        filename.write("            if (regs[i].has_access(UVM_REG_ACCESS_RW)) begin\n")
        filename.write("                uvm_reg_data_t wdata = {$urandom()} & ((1 << regs[i].get_n_bits()) - 1);\n")
        filename.write("                regs[i].write(status, wdata, UVM_FRONTDOOR);\n")
        filename.write("                if (status == UVM_IS_OK) begin\n")
        filename.write("                    regs[i].read(status, rdata, UVM_FRONTDOOR);\n")
        filename.write("                    if (rdata !== wdata) begin\n")
        filename.write("                        `uvm_error(get_type_name(), $sformatf(\n")
        filename.write("                            \"Readback mismatch: %%s: wrote %%0h, read %%0h\",\n")
        filename.write("                            rname, wdata, rdata))\n")
        filename.write("                        fail_cnt++;\n")
        filename.write("                    end\n")
        filename.write("                    else begin\n")
        filename.write("                        `uvm_info(get_type_name(), $sformatf(\"  PASS: %%s R/W test\", rname), UVM_HIGH)\n")
        filename.write("                        pass_cnt++;\n")
        filename.write("                    end\n")
        filename.write("                end\n")
        filename.write("                // 写回复位值\n")
        filename.write("                regs[i].write(status, regs[i].get_reset(), UVM_FRONTDOOR);\n")
        filename.write("            end\n")
        filename.write("        end\n")
        filename.write("\n")
        filename.write("        `uvm_info(get_type_name(), $sformatf(\"===== Reg Access Test Done: %%0d pass, %%0d fail =====\", pass_cnt, fail_cnt), UVM_LOW)\n")
        filename.write("    endtask : body\n")
        filename.write("\n")
        filename.write("endclass : %s_reg_access_seq\n" % tb_name)
        filename.write("\n")

        # ===== 2. Bit Bash Sequence =====
        filename.write("//=========================================================================\n")
        filename.write("// %s_reg_bit_bash_seq: 位翻转测试\n" % tb_name)
        filename.write("//   对每个 RW 寄存器执行:\n")
        filename.write("//   - Walking-1: 依次将每一位设为 1，其余为 0，写入后读回比对\n")
        filename.write("//   - Walking-0: 依次将每一位设为 0，其余为 1，写入后读回比对\n")
        filename.write("//=========================================================================\n")
        filename.write("class %s_reg_bit_bash_seq extends uvm_sequence;\n" % tb_name)
        filename.write("\n")
        filename.write("    %s_reg_block  regmodel;\n" % tb_name)
        filename.write("    uvm_status_e  status;\n")
        filename.write("\n")
        filename.write("    `uvm_object_utils(%s_reg_bit_bash_seq)\n" % tb_name)
        filename.write("    function new(string name=\"%s_reg_bit_bash_seq\");\n" % tb_name)
        filename.write("        super.new(name);\n")
        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("    virtual task body();\n")
        filename.write("        uvm_reg regs[$];\n")
        filename.write("        uvm_reg_data_t rdata, wdata, bitmask;\n")
        filename.write("        int pass_cnt, fail_cnt;\n")
        filename.write("        int n_bits;\n")
        filename.write("\n")
        filename.write("        `uvm_info(get_type_name(), \"===== Register Bit Bash Test Start =====\", UVM_LOW)\n")
        filename.write("\n")
        filename.write("        if (regmodel == null)\n")
        filename.write("            `uvm_fatal(get_type_name(), \"regmodel is null!\")\n")
        filename.write("\n")
        filename.write("        regmodel.get_registers(regs);\n")
        filename.write("        pass_cnt = 0; fail_cnt = 0;\n")
        filename.write("\n")
        filename.write("        foreach (regs[i]) begin\n")
        filename.write("            if (!regs[i].has_access(UVM_REG_ACCESS_RW))\n")
        filename.write("                continue;\n")
        filename.write("\n")
        filename.write("            n_bits = regs[i].get_n_bits();\n")
        filename.write("            string rname = regs[i].get_full_name();\n")
        filename.write("\n")
        filename.write("            // ----- Walking-1 -----\n")
        filename.write("            for (int b = 0; b < n_bits; b++) begin\n")
        filename.write("                bitmask = 1 << b;\n")
        filename.write("                regs[i].write(status, bitmask, UVM_FRONTDOOR);\n")
        filename.write("                if (status == UVM_IS_OK) begin\n")
        filename.write("                    regs[i].read(status, rdata, UVM_FRONTDOOR);\n")
        filename.write("                    if (rdata !== bitmask) begin\n")
        filename.write("                        `uvm_error(get_type_name(), $sformatf(\n")
        filename.write("                            \"Walking-1 FAIL: %%s bit%%0d: exp=%%0h, got=%%0h\",\n")
        filename.write("                            rname, b, bitmask, rdata))\n")
        filename.write("                        fail_cnt++;\n")
        filename.write("                    end\n")
        filename.write("                    else begin\n")
        filename.write("                        pass_cnt++;\n")
        filename.write("                    end\n")
        filename.write("                end\n")
        filename.write("            end\n")
        filename.write("\n")
        filename.write("            // ----- Walking-0 -----\n")
        filename.write("            for (int b = 0; b < n_bits; b++) begin\n")
        filename.write("                bitmask = ~(1 << b) & ((1 << n_bits) - 1);\n")
        filename.write("                regs[i].write(status, bitmask, UVM_FRONTDOOR);\n")
        filename.write("                if (status == UVM_IS_OK) begin\n")
        filename.write("                    regs[i].read(status, rdata, UVM_FRONTDOOR);\n")
        filename.write("                    if (rdata !== bitmask) begin\n")
        filename.write("                        `uvm_error(get_type_name(), $sformatf(\n")
        filename.write("                            \"Walking-0 FAIL: %%s bit%%0d: exp=%%0h, got=%%0h\",\n")
        filename.write("                            rname, b, bitmask, rdata))\n")
        filename.write("                        fail_cnt++;\n")
        filename.write("                    end\n")
        filename.write("                    else begin\n")
        filename.write("                        pass_cnt++;\n")
        filename.write("                    end\n")
        filename.write("                end\n")
        filename.write("            end\n")
        filename.write("\n")
        filename.write("            // 恢复复位值\n")
        filename.write("            regs[i].write(status, regs[i].get_reset(), UVM_FRONTDOOR);\n")
        filename.write("            `uvm_info(get_type_name(), $sformatf(\"  Done: %%s (%%0d bits)\", rname, n_bits), UVM_MEDIUM)\n")
        filename.write("        end\n")
        filename.write("\n")
        filename.write("        `uvm_info(get_type_name(), $sformatf(\"===== Bit Bash Done: %%0d pass, %%0d fail =====\", pass_cnt, fail_cnt), UVM_LOW)\n")
        filename.write("    endtask : body\n")
        filename.write("\n")
        filename.write("endclass : %s_reg_bit_bash_seq\n" % tb_name)
        filename.write("\n")

        # ===== 3. Stress Sequence =====
        filename.write("//=========================================================================\n")
        filename.write("// %s_reg_stress_seq: 随机读写压力测试\n" % tb_name)
        filename.write("//   对每个 RW 寄存器执行 N 次随机写入+读回比对\n")
        filename.write("//   默认 N=100，可通过 reg_stress_count 配置\n")
        filename.write("//=========================================================================\n")
        filename.write("class %s_reg_stress_seq extends uvm_sequence;\n" % tb_name)
        filename.write("\n")
        filename.write("    %s_reg_block  regmodel;\n" % tb_name)
        filename.write("    uvm_status_e  status;\n")
        filename.write("    int           reg_stress_count = 100;  // 每寄存器随机读写次数\n")
        filename.write("\n")
        filename.write("    `uvm_object_utils(%s_reg_stress_seq)\n" % tb_name)
        filename.write("    function new(string name=\"%s_reg_stress_seq\");\n" % tb_name)
        filename.write("        super.new(name);\n")
        filename.write("    endfunction\n")
        filename.write("\n")
        filename.write("    virtual task body();\n")
        filename.write("        uvm_reg regs[$];\n")
        filename.write("        uvm_reg_data_t rdata, wdata;\n")
        filename.write("        int pass_cnt, fail_cnt;\n")
        filename.write("\n")
        filename.write("        `uvm_info(get_type_name(), \"===== Register Stress Test Start =====\", UVM_LOW)\n")
        filename.write("\n")
        filename.write("        if (regmodel == null)\n")
        filename.write("            `uvm_fatal(get_type_name(), \"regmodel is null!\")\n")
        filename.write("\n")
        filename.write("        regmodel.get_registers(regs);\n")
        filename.write("        pass_cnt = 0; fail_cnt = 0;\n")
        filename.write("\n")
        filename.write("        repeat (reg_stress_count) begin\n")
        filename.write("            foreach (regs[i]) begin\n")
        filename.write("                if (!regs[i].has_access(UVM_REG_ACCESS_RW))\n")
        filename.write("                    continue;\n")
        filename.write("\n")
        filename.write("                // 随机写入\n")
        filename.write("                wdata = {$urandom()} & ((1 << regs[i].get_n_bits()) - 1);\n")
        filename.write("                regs[i].write(status, wdata, UVM_FRONTDOOR);\n")
        filename.write("                if (status != UVM_IS_OK) begin\n")
        filename.write("                    fail_cnt++;\n")
        filename.write("                    continue;\n")
        filename.write("                end\n")
        filename.write("\n")
        filename.write("                // 读回比对\n")
        filename.write("                regs[i].read(status, rdata, UVM_FRONTDOOR);\n")
        filename.write("                if (rdata !== wdata) begin\n")
        filename.write("                    `uvm_error(get_type_name(), $sformatf(\n")
        filename.write("                        \"Stress FAIL: %%s: wrote %%0h, read %%0h\",\n")
        filename.write("                        regs[i].get_full_name(), wdata, rdata))\n")
        filename.write("                    fail_cnt++;\n")
        filename.write("                end\n")
        filename.write("                else begin\n")
        filename.write("                    pass_cnt++;\n")
        filename.write("                end\n")
        filename.write("            end\n")
        filename.write("        end\n")
        filename.write("\n")
        filename.write("        `uvm_info(get_type_name(), $sformatf(\"===== Stress Done: %%0d pass, %%0d fail =====\", pass_cnt, fail_cnt), UVM_LOW)\n")
        filename.write("    endtask : body\n")
        filename.write("\n")
        filename.write("endclass : %s_reg_stress_seq\n" % tb_name)
        filename.write("\n")
        filename.write("`endif\n")
        
        filename.close()
        
        if PrintEnable:
            print("[gen_reg_sequence] %s_reg_sequence.sv generated" % tb_name)
            print("  - reg_access_seq: 复位值检查 + 读写比对")
            print("  - reg_bit_bash_seq: walking-1/walking-0")
            print("  - reg_stress_seq: 随机压力测试")


if __name__ == '__main__':
    gen = gen_reg_sequence()

